"""离线批量生成唯一解谜题, 输出 puzzles_pool.js (供 play.html 嵌入)."""

from __future__ import annotations

import json
import time
from pathlib import Path

from cow_puzzle import generate

# 每个尺寸要生成多少题
TARGETS = {
    8: 30,
    9: 15,
    10: 8,
}

# 单题最长允许时间 (秒). 超过就放弃这次种子, 换下一颗.
PER_PUZZLE_BUDGET_S = 30.0


def bake() -> dict[int, list[list[str]]]:
    out: dict[int, list[list[str]]] = {}
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    for n, count in TARGETS.items():
        print(f"\n=== N={n}  目标 {count} 题 ===")
        puzzles: list[list[str]] = []
        seed = 0
        while len(puzzles) < count:
            seed += 1
            t = time.perf_counter()
            try:
                grid, sol, n_sols = generate(n, seed=seed, want_unique=True,
                                              max_tries=80_000)
            except Exception as e:
                print(f"  seed={seed}: err {e}")
                continue
            dt = time.perf_counter() - t
            if n_sols == 1:
                rows = ["".join(digits[v] for v in row) for row in grid]
                puzzles.append(rows)
                print(f"  [{len(puzzles)}/{count}] seed={seed}  {dt:.1f}s  ✓")
            else:
                print(f"  seed={seed}: 多解 ({dt:.1f}s), 跳过")
            if dt > PER_PUZZLE_BUDGET_S:
                continue
        out[n] = puzzles
    return out


def main() -> None:
    pool = bake()
    out_path = Path(__file__).parent / "puzzles_pool.js"
    body = json.dumps(pool, ensure_ascii=False, indent=2)
    out_path.write_text(f"// Auto-generated by bake_puzzles.py — 不要手改\nwindow.PUZZLE_POOL = {body};\n",
                        encoding="utf-8")
    print(f"\n写入 {out_path}")
    for n, lst in pool.items():
        print(f"  N={n}: {len(lst)} 题")


if __name__ == "__main__":
    main()
